In [11]:
import numpy as np

**Question 1**:
Create a null vector of size 10 but the fifth value which is 1.

In [12]:
x = np.zeros(10)
x[4] = 1
print(x)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Question 2:** Create a vector with values ranging from 10 to 49.

In [13]:
x = np.arange(10,50)
print(x)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**Question 3 :** Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
x = np.arange(9)
v = x.reshape(3,3)
print(v)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Question 4 :** Find indices of non-zero elements from [1,2,0,0,4,0]

In [15]:
x = np.nonzero( [1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)

**Question 5 :** Create a 10x10 array with random values and find the minimum and maximum values.

In [18]:
x = np.random.random((10,10))
minval= x.min()
maxval= x.max()
print(minval)
print(maxval)


0.00257570125832729

**Question 6 :** Create a random vector of size 30 and find the mean value.

In [19]:
x = np.random.random(30)
meanval= x.mean()
print(meanval)

0.4709116930604377
